using HananokiLib;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Windows.Forms;


namespace MO2ModListUtls {

	public partial class MainForm : Form {

		static MainForm instance;

		public Config m_config;

		List<LVItem> m_itemsL = new List<LVItem>();
		List<LVItem> m_itemsR = new List<LVItem>();

		public Timer timer2;



		public static Config config => instance.m_config;




		public MainForm() {
			InitializeComponent();
			instance = this;
		}


		void MainForm_Load( object sender, EventArgs e ) {
			Font = SystemFonts.IconTitleFont;
			listView1.SetDoubleBuffered( true );
			listView2.SetDoubleBuffered( true );

			Helper.ReadJson( ref m_config, Helper.configPath );

			rollbackWindow();
		}


		void MainForm_Shown( object sender, EventArgs e ) {
			var a = new Form1( this );
			a.ShowDialog();


			//var aa = File.ReadAllLines( m_config.filePathBase );
			//m_itemsL = new List<LVItem>( aa .Length);
			//foreach(var s in aa) {
			//	if( string.IsNullOrEmpty( s ) ) continue;
			//	if( s[ 0 ] == '#' ) continue;
			//	if( s[ 0 ] == '*' ) continue;

			//	LVItem ii = new LVItem();

			//	var newItem = new ListViewItem( new string[] { s .Remove(0,1) } );
			//	newItem.Checked = true;
			//	if( s[ 0 ] == '+' ) {
			//		newItem.Checked = true;
			//	}
			//	else {
			//		newItem.Checked = false;
			//	}
			//	ii.item = newItem;

			//	m_itemsL.Add( ii );
			//}
			//listView1.VirtualListSize = m_itemsL.Count;
			//listView1.Columns[ 0 ].Width = listView1.Width - 4;

			if( !m_config.baseModListFilePath .isExistsFile()) {
				MessageBox.Show( "「ベースにするMODリスト」の読み込みに失敗しました", "Error" );
				Close();
				return;
			}
			if( !m_config.replaceModListFilePath.isExistsFile() ) {
				MessageBox.Show( "「書き換えたいMODリスト」の読み込みに失敗しました", "Error" );
				Close();
				return;
			}

			initListView( ref m_itemsL, listView1, m_config.baseModListFilePath, true );
			initListView( ref m_itemsR, listView2, m_config.replaceModListFilePath );

			if( m_itemsL.Count != m_itemsR.Count ) {
				MessageBox.Show( "Mod数に違いがあります", "Warning" );
			}

			initTimerProcess();
		}




		void MainForm_FormClosing( object sender, FormClosingEventArgs e ) {
			backupWindow();
			Helper.WriteJson( m_config );
		}



		void toolStripButton1_Click( object sender, EventArgs e ) {
			var items = new List<LVItem>( m_itemsL.Count );
			for( int i = 0; i < m_itemsL.Count; i++ ) {
				LVItem newLVItem = new LVItem();
				var newItem = new ListViewItem( new string[] { m_itemsL[ i ].item.Text } );
				newLVItem.item = newItem;
				newItem.Checked = true;
				//newItem.Checked = false;
				items.Add( newLVItem );
				newItem.invalidate();
				var find = m_itemsR.Find( x => x.item.Text == newItem.Text );
				if( find != null ) {
					newItem.Checked = find.item.Checked;
				}
				if( m_itemsL[ i ].item.Checked == true
					&& newItem.Checked == false ) {
					newItem.BackColor = Color.Pink;
				}
				//m_itemsR[ i ].item.Text = m_itemsL[ i ].item.Text;
				//m_itemsR[ i ].item.Invalidate(  );
			}
			m_itemsR = items;
			listView2.VirtualListSize = 0;
			listView2.VirtualListSize = m_itemsR.Count;
		}



		void toolStripButton2_Click( object sender, EventArgs e ) {

			var ss = DateTime.Now.ToString().Replace( "/", "" ).Replace( " ", "_" ).Replace( ":", "" );
			fs.mv( m_config.replaceModListFilePath, $"{m_config.replaceModListFilePath}.{ss}" );
			//return;

			var outputs = new List<string>();
			outputs.Add( "# This file was automatically generated by Mod Organizer." );
			foreach( var s in m_itemsR.Select( x => x.item ).Reverse() ) {
				var add = "-";
				if( s.Checked ) {
					add = "+";
				}
				outputs.Add( $"{add}{s.Text}" );
			}
			foreach( var s in requiredMod.AsEnumerable().Reverse() ) {
				outputs.Add( s );
			}
			File.WriteAllLines( m_config.replaceModListFilePath, outputs );

			MessageBox.Show( $@"{m_config.replaceModListFilePath} を上書きしました。
元のファイルは {m_config.replaceModListFilePath}.{ss} にバックアップしました。", "情報" );
		}



	}
}
